# Default initial positions for ros2_control simulation
initial_positions:
  shoulder_pan_joint: 0.0
  shoulder_lift_joint: -1.5708
  elbow_joint: 1.5708
  wrist_1_joint: -1.5708
  wrist_2_joint: -1.5708
  wrist_3_joint: 0.0
  gripper_robotiq_85_left_knuckle_joint: 0.0
