# Joint limits for MoveIt planning
# Based on UR5e specifications

# For smoother motion, we downscale velocity and acceleration.
# Increase these values (up to 1.0) for faster but less smooth motion.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  rbkairos_arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.0943
    has_acceleration_limits: true
    max_acceleration: 3.75
  rbkairos_arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.0943
    has_acceleration_limits: true
    max_acceleration: 1.875
  rbkairos_arm_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 2.5
  rbkairos_arm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.125
  rbkairos_arm_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 3.75
  rbkairos_arm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: true
    max_acceleration: 5.0
  rbkairos_gripper_robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.0
